"""first

Revision ID: 635469c85bf6
Revises: 
Create Date: 2022-09-27 11:42:10.951514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635469c85bf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('USD_relative_value', sa.Numeric(), nullable=False),
    sa.Column('available_quantity', sa.Numeric(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opening_date', sa.Text(), nullable=False),
    sa.Column('closing_date', sa.Text(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('operation_type', sa.Text(), nullable=False),
    sa.Column('currency_num_spent', sa.Numeric(), nullable=False),
    sa.Column('currency_num_obtained', sa.Numeric(), nullable=False),
    sa.Column('date_time', sa.Text(), nullable=False),
    sa.Column('account_from_which_the_transaction', sa.Numeric(), nullable=False),
    sa.Column('account_on_which_the_transaction', sa.Numeric(), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction_history')
    op.drop_table('rating')
    op.drop_table('deposit')
    op.drop_table('currency')
    op.drop_table('account')
    # ### end Alembic commands ###
