"""Bug Fix

Revision ID: 71aca1774d23
Revises: e9bb5097ff77
Create Date: 2022-09-27 12:24:53.631872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71aca1774d23'
down_revision = 'e9bb5097ff77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
