"""Second

Revision ID: e9bb5097ff77
Revises: 635469c85bf6
Create Date: 2022-09-27 11:59:55.001456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bb5097ff77'
down_revision = '635469c85bf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_history', sa.Column('queue_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_history', 'queue_id')
    # ### end Alembic commands ###
